#!/usr/bin/env node

/* eslint strict:"off" */
"use strict";

/**
 * Name: app
 * Description: Server api rest, files static
 * Main Module: www
 * Author: stephen D.
 * Version: 1.0.0
 */

const { build } = require("./build");

async function start() {
  const app = build({ logger: true });
  try {
    await app.listen(3000);
  } catch (err) {
    app.log.error(err);
    process.exit(1);
  }
}

if (require.main === module) {
  start();
}
